language: node_js
node_js:
  - "0.10"

before_install:
  - npm install
  - npm install -g bower
  - bower install

addons:
  sauce_connect:
    username: "joejknowles"
    access_key: "e56a01c3-1d15-476f-b655-957a0a73d204"

script:
  - protractor test/e2e/conf.js